SRD-20 dodano przykładowe quizy
XT60/Srednia-hawajska pull request #4
Opened 2024-05-13 13:51 UTC by Ember404

Przykładowe qiuzy, wyznaczające format, w jakim będą przechowywane. Podczas review proszę o sprawdzenie czy taka forma zapisu błędów jedno i wielo linijkowych będzie odpowiednia.

2024-05-13 15:17 UTC, anian3 commented on Example_qiuzes/cpp/code/file1cpp.txt
Typo - Example_quizes ? 
Why is this file empty?

2024-05-13 15:17 UTC, anian3 commented on Example_qiuzes/cpp/smell_list/file1cpp.json
> +    "language": "python",
In folder cpp but language is python

2024-05-13 15:17 UTC, anian3 commented on Example_qiuzes/python/code/file2.txt
are file1 and file2 identical on purpose?

2024-05-13 19:12 UTC, cwiertniak approved these changes

2024-05-13 21:19 UTC, tranquilo-01 commented
Moim zdaniem przechowywanie code smelli w takiej formie jak jest opisana w Docs/api.md jest lepsze. Tutaj ciężej będzie napisać funkcję, która rozpoznaje czy code smelle są dobrze zaznaczone. Wydaje mi się że łatwiej jest poruszać się po jsonie, gdzie kategoria code smella jest wartością a nie kluczem, ale pozostawiam kwestię do dyskusji. Mam też pewne obiekcje co do struktury katalogów, ale to chyba nie jest przedmiotem tego PRa, moja propozycja jest w Docs/api.md

2024-05-14 08:32 UTC, Polokratos commented
> Moim zdaniem przechowywanie code smelli w takiej formie jak jest opisana w Docs/api.md jest lepsze. Tutaj ciężej będzie napisać funkcję, która rozpoznaje czy code smelle są dobrze zaznaczone. Wydaje mi się że łatwiej jest poruszać się po jsonie, gdzie kategoria code smella jest wartością a nie kluczem, ale pozostawiam kwestię do dyskusji. Mam też pewne obiekcje co do struktury katalogów, ale to chyba nie jest przedmiotem tego PRa, moja propozycja jest w Docs/api.md

+1. Kategoria code smella jest rzeczą mało istotną z perspektywy aplikacji - ot coś do wyświetlenia na froncie.
Lepiej mieć wszystkie code smelle w jednej liście i nawet jeżeli będziemy duplikować tekst kategorii to nas to nie boli jakoś bardzo.

2024-05-14 08:34 UTC, Polokratos requested changes
Jsony są niezgodne z proponowanym api - jest decyzja do podjęcia jak chcemy iść dalej

2024-05-14 09:43 UTC, Ember404 commented
> Moim zdaniem przechowywanie code smelli w takiej formie jak jest opisana w Docs/api.md jest lepsze. Tutaj ciężej będzie napisać funkcję, która rozpoznaje czy code smelle są dobrze zaznaczone. Wydaje mi się że łatwiej jest poruszać się po jsonie, gdzie kategoria code smella jest wartością a nie kluczem, ale pozostawiam kwestię do dyskusji. Mam też pewne obiekcje co do struktury katalogów, ale to chyba nie jest przedmiotem tego PRa, moja propozycja jest w Docs/api.md

Nie zauważyłam opisu konwencji api. Struktura plików jest jak najbardziej do dogadania, ale przy tworzeniu tych jsonów miałam na uwadze wygodę admina, który będzie tworzył quizy. Łatwiej mu będzie powpisywać błędy do danej kategorii, niż wypisywać całą listę. Jeśli wygoda tworzenia qiuzów nie jest istotna, jak najbardziej możemy trzymać się konwencji opisanej w Docs/api.md.
@Polokratos  decyzja należy do ciebie jako do PO.

2024-05-14 09:46 UTC, Polokratos commented
> > Moim zdaniem przechowywanie code smelli w takiej formie jak jest opisana w Docs/api.md jest lepsze. Tutaj ciężej będzie napisać funkcję, która rozpoznaje czy code smelle są dobrze zaznaczone. Wydaje mi się że łatwiej jest poruszać się po jsonie, gdzie kategoria code smella jest wartością a nie kluczem, ale pozostawiam kwestię do dyskusji. Mam też pewne obiekcje co do struktury katalogów, ale to chyba nie jest przedmiotem tego PRa, moja propozycja jest w Docs/api.md
> 
> Nie zauważyłam opisu konwencji api. Struktura plików jest jak najbardziej do dogadania, ale przy tworzeniu tych jsonów miałam na uwadze wygodę admina, który będzie tworzył quizy. Łatwiej mu będzie powpisywać błędy do danej kategorii, niż wypisywać całą listę. Jeśli wygoda tworzenia qiuzów nie jest istotna, jak najbardziej możemy trzymać się konwencji opisanej w Docs/api.md. @Polokratos decyzja należy do ciebie jako do PO.

Jeżeli adminowi będzie niewygodnie robić po naszemu, to się dorobi konwerter który równie dobrze może być CLI IMO.

2024-05-14 09:54 UTC, Polokratos approved these changes

2024-05-19 10:23 UTC, merged